
var snowflake = Snowflake(side: 13)
snowflake.show()
snowflake.thaw()
print("\n------------------\n")
snowflake.show()
snowflake.thaw()
print("\n------------------\n")
snowflake.show()
snowflake.thicken()
print("\n------------------\n")
snowflake.show()
snowflake.thicken()
print("\n------------------\n")
snowflake.show()

snowflake.thaw()
print("\n------------------\n")
snowflake.show()
snowflake.thaw()
print("\n------------------\n")
snowflake.show()
snowflake.thaw()
print("\n------------------\n")
snowflake.show()
